### ISSUE TITLE
valid-package-file-require lints "./../file.js" as invalid

### ISSUE THREAD

**Issue by edg2s** [wikimedia/eslint-plugin-mediawiki#18]
Even though this appears to be valid syntax.

CC @jakobw @Ladsgroup

**Comment by jakobw** [comment]
True, `./../file.js` is valid but the `./` doesn't do anything, right? `../file.js` would work just as well.

I guess it's fair to say that a rule claiming to lint for _valid_ require syntax shouldn't be opinionated about anything beyond validity.

**Comment by edg2s** [comment]
Indeed, and from my testing `./../` appears to be quite popular for whatever reason...
