### ISSUE TITLE
Link to documentation pages for class-doc/msg-doc

### ISSUE THREAD

**Issue by kostajh** [wikimedia/eslint-plugin-mediawiki#25]
I don't know if one exists yet, but would be helpful to prioritize since we now start throwing errors when this rule isn't met. It wasn't obvious to me that it had to follow this specific format, I've always just used `// message-key` in a line above its usage. And I imagine others will get confused by this too.

https://github.com/wikimedia/eslint-plugin-mediawiki/blob/296d7d42bf05594598ed6155367dfcf0aacb0a7e/rules/msg-doc.js#L32

(btw, thanks for adding this rule -- it's quite useful!)

**Comment by jdforrester** [comment]
It's in https://www.mediawiki.org/wiki/Localisation#Using_messages but only for PHP; should we add an example in JS too and mention that it's enforced?
