### ISSUE TITLE
Create a rule to enforce documentation of constructed CSS classes

### ISSUE THREAD

**Issue by edg2s** [wikimedia/eslint-plugin-mediawiki#3]
For example:
```js
// The follow classes are used here:
// * ve-init-target-visual
// * ve-init-target-source
this.$element.addClass( 've-init-target-' + defaultMode );
```

We would need to detect jQuery, OOUI and plain JS APIs for adding classes.

**Comment by edg2s** [comment]
#12 adds support for jQuery, but OOUI & plain JS are TODO

**Comment by jdforrester** [comment]
Done?

**Comment by edg2s** [comment]
After this DOM patch we can call it "done". There will always be edge cases (e.g. .attr('class', 'foo')) but it's diminishing returns.

Even the DOM patch didn't find any violations in MW core.
